In [1]:
import numpy as np
import onnxruntime as ort
import cv2


In [2]:
# img = np.load("./examples/01.AlexandraUrsu.jpg").reshape(1, 224, 224, 3)
# print(img)

new_img = cv2.cvtColor(cv2.imread("./examples/01.AlexandraUrsu.jpg"),cv2.COLOR_BGR2RGB) # convert to RGB -- use this for display          
# convert the image for modelling
test_img = np.array(new_img, dtype=float)
print(test_img)
test_img = test_img/255
print(test_img)
print(np.array(test_img))
# test_img = np.array(test_img).reshape(1, 224, 224, 3) 

[[[172. 163. 146.]
  [171. 162. 145.]
  [169. 160. 143.]
  ...
  [108.  99.  84.]
  [110. 101.  86.]
  [114. 105.  90.]]

 [[173. 164. 147.]
  [173. 164. 147.]
  [172. 163. 146.]
  ...
  [109. 100.  85.]
  [108.  99.  84.]
  [111. 102.  87.]]

 [[172. 163. 146.]
  [172. 163. 146.]
  [173. 164. 147.]
  ...
  [110. 101.  86.]
  [108.  99.  84.]
  [110. 101.  86.]]

 ...

 [[127. 128. 133.]
  [130. 131. 136.]
  [131. 132. 137.]
  ...
  [203. 207. 216.]
  [198. 202. 211.]
  [194. 198. 207.]]

 [[127. 128. 133.]
  [131. 132. 137.]
  [133. 134. 139.]
  ...
  [205. 209. 218.]
  [201. 205. 214.]
  [197. 201. 210.]]

 [[120. 121. 126.]
  [124. 125. 130.]
  [126. 127. 132.]
  ...
  [204. 208. 217.]
  [202. 206. 215.]
  [198. 202. 211.]]]
[[[0.6745098  0.63921569 0.57254902]
  [0.67058824 0.63529412 0.56862745]
  [0.6627451  0.62745098 0.56078431]
  ...
  [0.42352941 0.38823529 0.32941176]
  [0.43137255 0.39607843 0.3372549 ]
  [0.44705882 0.41176471 0.35294118]]

 [[0.67843137 0.64313725 0.57647

In [3]:
sess_ort = ort.InferenceSession("./modelFaceShape.onnx")
print(sess_ort)

In [4]:
res = sess_ort.run(None, {test_img})
print(res)

TypeError: unhashable type: 'numpy.ndarray'